// Date: 4/21/2014 11:21:36 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package psychicnova.matches;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelHeroBoss extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarmtop;
    ModelRenderer leftarmtop;
    ModelRenderer rightlegtop;
    ModelRenderer leftlegtop;
    ModelRenderer leftlegbottom;
    ModelRenderer rightlegbottom;
    ModelRenderer leftarmbottom;
    ModelRenderer rightarmbottom;
  
  public ModelHeroBoss()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarmtop = new ModelRenderer(this, 40, 16);
      rightarmtop.addBox(-3F, -2F, -2F, 4, 6, 4);
      rightarmtop.setRotationPoint(-5F, 2F, 0F);
      rightarmtop.setTextureSize(64, 32);
      rightarmtop.mirror = true;
      setRotation(rightarmtop, 0F, 0F, 0F);
      leftarmtop = new ModelRenderer(this, 40, 16);
      leftarmtop.addBox(-1F, -2F, -2F, 4, 6, 4);
      leftarmtop.setRotationPoint(5F, 2F, 0F);
      leftarmtop.setTextureSize(64, 32);
      leftarmtop.mirror = true;
      setRotation(leftarmtop, 0F, 0F, 0F);
      rightlegtop = new ModelRenderer(this, 0, 16);
      rightlegtop.addBox(-2F, 0F, -2F, 4, 6, 4);
      rightlegtop.setRotationPoint(-2F, 12F, 0F);
      rightlegtop.setTextureSize(64, 32);
      rightlegtop.mirror = true;
      setRotation(rightlegtop, 0F, 0F, 0F);
      leftlegtop = new ModelRenderer(this, 0, 16);
      leftlegtop.addBox(-2F, 0F, -2F, 4, 6, 4);
      leftlegtop.setRotationPoint(2F, 12F, 0F);
      leftlegtop.setTextureSize(64, 32);
      leftlegtop.mirror = true;
      setRotation(leftlegtop, 0F, 0F, 0F);
      leftlegbottom = new ModelRenderer(this, 0, 16);
      leftlegbottom.addBox(-2F, 0F, -2F, 4, 6, 4);
      leftlegbottom.setRotationPoint(2F, 18F, 0F);
      leftlegbottom.setTextureSize(64, 32);
      leftlegbottom.mirror = true;
      setRotation(leftlegbottom, 0F, 0F, 0F);
      rightlegbottom = new ModelRenderer(this, 0, 16);
      rightlegbottom.addBox(-2F, 0F, -2F, 4, 6, 4);
      rightlegbottom.setRotationPoint(-2F, 18F, 0F);
      rightlegbottom.setTextureSize(64, 32);
      rightlegbottom.mirror = true;
      setRotation(rightlegbottom, 0F, 0F, 0F);
      leftarmbottom = new ModelRenderer(this, 40, 16);
      leftarmbottom.addBox(-1F, -2F, -2F, 4, 6, 4);
      leftarmbottom.setRotationPoint(5F, 8F, 0F);
      leftarmbottom.setTextureSize(64, 32);
      leftarmbottom.mirror = true;
      setRotation(leftarmbottom, 0F, 0F, 0F);
      rightarmbottom = new ModelRenderer(this, 40, 16);
      rightarmbottom.addBox(-3F, -2F, -2F, 4, 6, 4);
      rightarmbottom.setRotationPoint(-5F, 8F, 0F);
      rightarmbottom.setTextureSize(64, 32);
      rightarmbottom.mirror = true;
      setRotation(rightarmbottom, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    head.render(f5);
    body.render(f5);
    rightarmtop.render(f5);
    leftarmtop.render(f5);
    rightlegtop.render(f5);
    leftlegtop.render(f5);
    leftlegbottom.render(f5);
    rightlegbottom.render(f5);
    leftarmbottom.render(f5);
    rightarmbottom.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
}
